///
/// @Generated by Mockolo
///



import Vapor
@testable import App


public class SlackWebServicingMock: SlackWebServicing {
    public init() { }


    public var sendSlackPayloadCallCount = 0
    public var sendSlackPayloadHandler: ((String, Emoji?, Request) -> (EventLoopFuture<ClientResponse>))?
    public func sendSlackPayload(text: String, with emoji: Emoji?, on req: Request) -> EventLoopFuture<ClientResponse> {
        sendSlackPayloadCallCount += 1
        if let sendSlackPayloadHandler = sendSlackPayloadHandler {
            return sendSlackPayloadHandler(text, emoji, req)
        }
        fatalError("sendSlackPayloadHandler returns can't have a default value thus its handler must be set")
    }
}

public class FreshbooksWebServicingMock: FreshbooksWebServicing {
    public init() { }


    public var deleteWebhookCallCount = 0
    public var deleteWebhookHandler: ((String, Int, Request) -> (EventLoopFuture<Void>))?
    public func deleteWebhook(accountID: String, webhookID: Int, on req: Request) -> EventLoopFuture<Void> {
        deleteWebhookCallCount += 1
        if let deleteWebhookHandler = deleteWebhookHandler {
            return deleteWebhookHandler(accountID, webhookID, req)
        }
        fatalError("deleteWebhookHandler returns can't have a default value thus its handler must be set")
    }

    public var registerNewWebhookCallCount = 0
    public var registerNewWebhookHandler: ((String, String, WebhookType, Client) -> (EventLoopFuture<NewWebhookPayloadCallback>))?
    public func registerNewWebhook(accountID: String, accessToken: String, type: WebhookType, with client: Client) -> EventLoopFuture<NewWebhookPayloadCallback> {
        registerNewWebhookCallCount += 1
        if let registerNewWebhookHandler = registerNewWebhookHandler {
            return registerNewWebhookHandler(accountID, accessToken, type, client)
        }
        fatalError("registerNewWebhookHandler returns can't have a default value thus its handler must be set")
    }

    public var fetchWebhooksCallCount = 0
    public var fetchWebhooksHandler: ((String, String, Int, Request) -> (EventLoopFuture<WebhookResponseResult>))?
    public func fetchWebhooks(accountID: String, accessToken: String, page: Int, req: Request) -> EventLoopFuture<WebhookResponseResult> {
        fetchWebhooksCallCount += 1
        if let fetchWebhooksHandler = fetchWebhooksHandler {
            return fetchWebhooksHandler(accountID, accessToken, page, req)
        }
        fatalError("fetchWebhooksHandler returns can't have a default value thus its handler must be set")
    }

    public var fetchInvoiceCallCount = 0
    public var fetchInvoiceHandler: ((String, Int, String, Request) -> (EventLoopFuture<InvoiceContent>))?
    public func fetchInvoice(accountID: String, invoiceID: Int, accessToken: String, req: Request) -> EventLoopFuture<InvoiceContent> {
        fetchInvoiceCallCount += 1
        if let fetchInvoiceHandler = fetchInvoiceHandler {
            return fetchInvoiceHandler(accountID, invoiceID, accessToken, req)
        }
        fatalError("fetchInvoiceHandler returns can't have a default value thus its handler must be set")
    }

    public var fetchClientCallCount = 0
    public var fetchClientHandler: ((String, Int, String, Request) -> (EventLoopFuture<ClientContent>))?
    public func fetchClient(accountID: String, clientID: Int, accessToken: String, req: Request) -> EventLoopFuture<ClientContent> {
        fetchClientCallCount += 1
        if let fetchClientHandler = fetchClientHandler {
            return fetchClientHandler(accountID, clientID, accessToken, req)
        }
        fatalError("fetchClientHandler returns can't have a default value thus its handler must be set")
    }

    public var fetchPaymentCallCount = 0
    public var fetchPaymentHandler: ((String, Int, String, Request) -> (EventLoopFuture<PaymentContent>))?
    public func fetchPayment(accountID: String, paymentID: Int, accessToken: String, req: Request) -> EventLoopFuture<PaymentContent> {
        fetchPaymentCallCount += 1
        if let fetchPaymentHandler = fetchPaymentHandler {
            return fetchPaymentHandler(accountID, paymentID, accessToken, req)
        }
        fatalError("fetchPaymentHandler returns can't have a default value thus its handler must be set")
    }

    public var fetchUserCallCount = 0
    public var fetchUserHandler: ((String, Request) -> (EventLoopFuture<UserResponseObject>))?
    public func fetchUser(accessToken: String, on req: Request) -> EventLoopFuture<UserResponseObject> {
        fetchUserCallCount += 1
        if let fetchUserHandler = fetchUserHandler {
            return fetchUserHandler(accessToken, req)
        }
        fatalError("fetchUserHandler returns can't have a default value thus its handler must be set")
    }

    public var fetchInvoicesCallCount = 0
    public var fetchInvoicesHandler: ((String, String, Int, Client) -> (EventLoopFuture<InvoicesMetaDataContent>))?
    public func fetchInvoices(accountID: String, accessToken: String, page: Int, with client: Client) -> EventLoopFuture<InvoicesMetaDataContent> {
        fetchInvoicesCallCount += 1
        if let fetchInvoicesHandler = fetchInvoicesHandler {
            return fetchInvoicesHandler(accountID, accessToken, page, client)
        }
        fatalError("fetchInvoicesHandler returns can't have a default value thus its handler must be set")
    }

    public var confirmWebhookCallCount = 0
    public var confirmWebhookHandler: ((String, String, Int, String, Request) -> (EventLoopFuture<Void>))?
    public func confirmWebhook(accessToken: String, accountID: String, objectID: Int, verifier: String, on req: Request) -> EventLoopFuture<Void> {
        confirmWebhookCallCount += 1
        if let confirmWebhookHandler = confirmWebhookHandler {
            return confirmWebhookHandler(accessToken, accountID, objectID, verifier, req)
        }
        fatalError("confirmWebhookHandler returns can't have a default value thus its handler must be set")
    }

    public var authCallCount = 0
    public var authHandler: ((String, Request) -> (EventLoopFuture<TokenExchangeResponse>))?
    public func auth(with code: String, on req: Request) -> EventLoopFuture<TokenExchangeResponse> {
        authCallCount += 1
        if let authHandler = authHandler {
            return authHandler(code, req)
        }
        fatalError("authHandler returns can't have a default value thus its handler must be set")
    }
}

